<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <RootNamespace>BusStationAPI.API</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Swashbuckle.AspNetCore" Version="6.5.0" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="9.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BusStationAPI.Application\BusStationAPI.Application.csproj" />
    <ProjectReference Include="..\BusStationAPI.Infrastructure\BusStationAPI.Infrastructure.csproj" />
    <ProjectReference Include="..\BusStationAPI.Domain\BusStationAPI.Domain.csproj" />
  </ItemGroup>
</Project>
