<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\PublicManagment.Domain\PublicManagment.Domain.csproj" />
    <ProjectReference Include="..\tierdwebapp\tierdwebapp.csproj" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\PublicManagment.Domain\PublicManagment.Domain.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Exceptions\" />
  </ItemGroup>

</Project>
